// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5oNLyCX9tiICMNCozzSH8ZoUbb_-7pg',
    appId: '1:197030308228:web:843dd782b2ddad70ca15d1',
    messagingSenderId: '197030308228',
    projectId: 'around-proj',
    authDomain: 'around-proj.firebaseapp.com',
    storageBucket: 'around-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9fkVAC-k5CJKF6FgHlv3_HwOlfFYNYc',
    appId: '1:197030308228:android:8435e452e66ee473ca15d1',
    messagingSenderId: '197030308228',
    projectId: 'around-proj',
    storageBucket: 'around-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWmzY2bBspz2AcbFvf9wHyoxSBAL8Rd-0',
    appId: '1:197030308228:ios:badc1e2d7f2935e1ca15d1',
    messagingSenderId: '197030308228',
    projectId: 'around-proj',
    storageBucket: 'around-proj.appspot.com',
    iosClientId: '197030308228-4p6dot65n2u67pnv39dsi6v8dvtqqkhm.apps.googleusercontent.com',
    iosBundleId: 'com.biton.around.around',
  );
}
