// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC91l2wND24cNIGx5jcpS6h0ZFpG8u-Fa4',
    appId: '1:153033030661:web:411adbcd201786e608706c',
    messagingSenderId: '153033030661',
    projectId: 'routee-d3f84',
    authDomain: 'routee-d3f84.firebaseapp.com',
    storageBucket: 'routee-d3f84.appspot.com',
    measurementId: 'G-ENQ139YCHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYgfXM9ZXE2Xh10IOXNKWJvVATsYOais',
    appId: '1:153033030661:android:41a4353550c61b4c08706c',
    messagingSenderId: '153033030661',
    projectId: 'routee-d3f84',
    storageBucket: 'routee-d3f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuOm4o5-0HYdvMqa-ilTPP6bZ9dJURjJ8',
    appId: '1:153033030661:ios:efd80d3c0afe1c0208706c',
    messagingSenderId: '153033030661',
    projectId: 'routee-d3f84',
    storageBucket: 'routee-d3f84.appspot.com',
    iosClientId: '153033030661-ni4rimgln73e1u7vlpoit0vr25njn5ke.apps.googleusercontent.com',
    iosBundleId: 'com.biton.routee',
  );
}
